# Generated by Django 4.2.6 on 2024-10-31 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 15), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(15, 10), verbose_name='終了時間')),
                ('is_holiday', models.BooleanField(default=False)),
            ],
        ),
    ]
