# Generated by Django 4.2.6 on 2024-10-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('s_num', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=64)),
                ('s_password', models.CharField(max_length=128)),
                ('s_mail', models.CharField(max_length=64, null=True)),
                ('s_class', models.CharField(max_length=64)),
                ('s_flag', models.BooleanField(default=True)),
            ],
        ),
    ]
