# Generated by Django 4.2.6 on 2024-11-26 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('date', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', '登校'), ('absent', '欠席'), ('late', '遅刻'), ('leave_early', '早退')], max_length=20)),
                ('attendance_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='date.calendar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
