# Generated by Django 4.2.6 on 2024-10-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
