# Generated by Django 4.2.6 on 2024-10-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='StudentProfile',
        ),
    ]
